/* eslint-disable @typescript-eslint/no-require-imports */
const { google } = require('googleapis');
const path = require('path');
const fs = require('fs');

// Configuration
const KEY_FILE_PATH = process.env.GOOGLE_APPLICATION_CREDENTIALS || path.join(__dirname, '..', 'captcha-1747281225780-8777cd95d4a8.json');
const STRATEGY_FILE = path.join(__dirname, 'strategy_output.json');

async function publishGmbPost() {
    // 1. Load the latest strategy generated by seo_optimizer.js
    if (!fs.existsSync(STRATEGY_FILE)) {
        console.log('No new strategy found to post.');
        return;
    }

    const strategyData = JSON.parse(fs.readFileSync(STRATEGY_FILE, 'utf8'));
    const gmbPostIdea = strategyData.gmb_post;

    if (!gmbPostIdea) {
        console.log('No GMB post idea found in strategy.');
        return;
    }

    // 2. Setup GMB Auth
    const auth = new google.auth.GoogleAuth({
        keyFile: KEY_FILE_PATH,
        scopes: ['https://www.googleapis.com/auth/business.manage'],
    });

    const mybusinessbusinessinformation = google.mybusinessbusinessinformation('v1');

    // Note: In 2026, posting is typically handled via the "Local Services" or "Business Information" endpoints depending on the specific update.
    // This script prepares the payload for the standard "Local Post" structure.

    try {
        const authClient = await auth.getClient();
        google.options({ auth: authClient });

        // 3. Get Account & Location (This requires the API to be active/whitelisted)
        const accountRes = await google.mybusinessaccountmanagement('v1').accounts.list();
        const accounts = accountRes.data.accounts;

        if (!accounts || accounts.length === 0) {
            throw new Error('No GMB accounts found. Is the service account a manager?');
        }

        const accountName = accounts[0].name; // Using the first account
        const locationRes = await mybusinessbusinessinformation.accounts.locations.list({
            parent: accountName,
            readMask: 'name,title'
        });

        const locations = locationRes.data.locations;
        if (!locations || locations.length === 0) {
            throw new Error('No locations found for this account.');
        }

        // 4. Publish to each location (Gonda, Lucknow, Noida)
        const isSunday = new Date().getDay() === 0;
        
        if (!isSunday && !process.env.FORCE_GMB_POST) {
            console.log('Skipping GMB post: Automation restricted to SUNDAYS for safety (Anti-Spam Policy).');
            return;
        }

        for (const location of locations) {
            console.log(`Publishing to: ${location.title}...`);

            try {
                // Using the v1 LocalPosts API
                await google.mybusinessbusinessinformation('v1').locations.localPosts.create({
                    parent: location.name,
                    requestBody: {
                        languageCode: 'en-US',
                        summary: gmbPostIdea,
                        topicType: 'STANDARD',
                        callToAction: {
                            actionType: 'LEARN_MORE',
                            url: 'https://smilefotilo.com'
                        }
                    }
                });
                console.log(`Successfully posted to ${location.title}`);
            } catch (postErr) {
                console.error(`Failed to post to ${location.title}:`, postErr.message);
                if (postErr.message.includes('Quota exceeded')) {
                    console.log('NOTICE: GMB API Quota is 0. Manual whitelisting required in Google Cloud Console.');
                }
            }
        }

        console.log('GMB Automation Cycle Complete.');
    } catch (err) {
        console.error('GMB Posting Error:', err.message);
        if (err.message.includes('Quota exceeded')) {
            console.log('NOTICE: GMB API is still in "0 Quota" mode. Awaiting Google whitelisting.');
        }
    }
}

publishGmbPost();
