name: Deploy to Vercel

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: team_mTjbTHdgrk1Xial2kB7YKqeo
  VERCEL_PROJECT_ID: prj_gYNg9gLZAsGsTLvRBmp8TCtJBA8y

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
